spring.application.name=pawpal-backend
spring.datasource.url=jdbc:mysql://localhost:3306/pawpaldb
spring.datasource.username=root
spring.datasource.password=PawpalRoot!2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
ml.service.url=http://localhost:8001
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB